### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE4iOS#1]
I cloned the repository, could open the project in Xcode, but could not compile. It's complaining about missing pod files. Do I need to add these myself and how? If not, can you please add them to the repository?

PS: I populated the _assetfolder and pushed that.

**Comment by ik2wxx** [comment]
Please install CocoaPods from here https://cocoapods.org/ then run "pod install" to download the pods.
CocoaPods is a dependency manager for Swift and Objective-C Cocoa projects.
BTW, the assets you pushed are not correct.
You should add the entire "assets" library from Android project into the CanZE/CanZE folder and rename it to "_assets" so that in the CanZE/CanZE folder you have _assets/ZOE, _assets/ZOE_Ph2, and so on, a total of 174 files.

**Comment by yoh-there** [comment]
I replaced the assets and pushed. This was successful.

Next I installed cocaopods using "sudo gem install cocoapods", following the directions on https://guides.cocaopods.org/using/getting-started.html. This again led to an error. "The compiler failed to generate an executable file" (I have attached the complete trace, renamed to .txt). The troubleshooting page did not help.

Help would be appreciated. Once done I will write the compile instructions in the readme.MD

NB: I assume it does not matter in which directory I am when installing when entering this command. If this is incorrect, please let me know what directory I need to be in when installing.
[gem_make.out.txt](https://github.com/fesch/CanZE4iOS/files/5932593/gem_make.out.txt)
